version: "3.8"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data-db:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql  
    networks:
      - mynetwork-pvt
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
    image: biswarup65/two-tier-flask:v5
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: db1
    depends_on:
      - mysql-db
    networks:
      - mynetwork-pvt
    restart: always
    healthcheck:
      test: ["CMD-SHELL", " curl -f http://localhost:5000/health || exit 1 "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mynetwork-pvt:

networks:
  mysql-data-db:

